name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all projects
      run: |
        for p in *
        do
          cd $p
          cargo build --verbose
          cd ..
        done
