name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all projects
      run: |
        for d in *
        do
          if [ -d $d ]
          then
            cd $d
            cargo build --verbose
          fi
        done

    - name: Test all projects
      run: |
        for d in *
        do
          if [ -d $d ]
          then
            cd $d
            cargo test --verbose
          fi
        done
